version: '3'

services:
  vnc_postgresql:
    image: postgres
    container_name: vnc_postgresql
    restart: always
    environment:
      - POSTGRES_DB=vnc_postgresql
      - POSTGRES_USER=vnc_postgresql_user
      - POSTGRES_PASSWORD=vnc_d4tab4s&
    volumes:
      - ./postgresql-init.sql:/docker-entrypoint-initdb.d/postgresql-init.sql
    ports:
      - "5435:5432"
    networks:
      - vnc_network

networks:
  vnc_network:
    external: true
